/**
 * DO NOT EDIT MANUALLY.
 * Generated by scripts/build-tokens.js from tokens.json (Tokens Studio / W3C DTCG Standard)
 */

export const tokens = {
  "global": {
    "color-gold": "#fdb518",
    "color-blue": "#1e3a5f",
    "color-slate-600": "#475569",
    "color-slate-700": "#334155",
    "color-slate-800": "#1e293b",
    "color-slate-900": "#0f172a",
    "color-slate-950": "#020617",
    "color-warm-bg": "#f7f3ec",
    "color-warm-card": "#fffdf9",
    "color-warm-text": "#2c2520",
    "color-warm-muted": "#8a8078",
    "spacing-xs": "4px",
    "spacing-sm": "8px",
    "spacing-md": "16px",
    "spacing-lg": "24px",
    "spacing-xl": "32px",
    "spacing-2xl": "48px",
    "border-radius-sm": "6px",
    "border-radius-md": "10px",
    "border-radius-lg": "16px",
    "border-radius-xl": "20px",
    "border-radius-pill": "9999px",
    "typography-font-family": "'Cairo', sans-serif",
    "typography-font-size-xs": "0.75rem",
    "typography-font-size-sm": "0.875rem",
    "typography-font-size-base": "1rem",
    "typography-font-size-lg": "1.125rem",
    "typography-font-size-xl": "1.25rem",
    "typography-font-size-2xl": "1.5rem",
    "typography-font-size-input-mobile": "16px",
    "typography-line-height-tight": "1.25",
    "typography-line-height-normal": "1.5",
    "typography-line-height-relaxed": "1.65",
    "box-shadow-sm": "0 1px 3px rgba(44, 37, 32, 0.04), 0 1px 2px rgba(44, 37, 32, 0.03)",
    "box-shadow-md": "0 4px 12px rgba(44, 37, 32, 0.06), 0 1px 4px rgba(44, 37, 32, 0.04)",
    "box-shadow-lg": "0 8px 24px rgba(44, 37, 32, 0.08), 0 2px 8px rgba(44, 37, 32, 0.04)",
    "box-shadow-xl": "0 16px 40px rgba(44, 37, 32, 0.1), 0 4px 12px rgba(44, 37, 32, 0.05)",
    "touch-target-min": "48px",
    "touch-target-clearance": "8px"
  },
  "component": {
    "product-card-aspect-ratio": "4 / 3",
    "product-card-radius": "16px",
    "product-card-image-bg": "#0f172a",
    "bottom-sheet-handle-width": "40px",
    "bottom-sheet-handle-height": "4px",
    "bottom-sheet-radius": "20px"
  },
  "semantic": {
    "shop1": {
      "primary": "#fdb518",
      "glow": "rgba(253, 181, 24, 0.15)"
    },
    "shop2": {
      "primary": "#1e3a5f",
      "glow": "rgba(30, 58, 95, 0.15)"
    }
  }
};
