/**
 * Automated Design Token Compiler (Tokens Studio / W3C DTCG Standard)
 * Compiles frontend/src/tokens/tokens.json into:
 *   - frontend/src/tokens/tokens.css (CSS Custom Properties)
 *   - frontend/src/tokens/tokens.js  (JavaScript Constants)
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const ROOT_DIR = path.resolve(__dirname, '..');
const TOKENS_JSON_PATH = path.join(ROOT_DIR, 'frontend', 'src', 'tokens', 'tokens.json');
const TOKENS_CSS_PATH = path.join(ROOT_DIR, 'frontend', 'src', 'tokens', 'tokens.css');
const TOKENS_JS_PATH = path.join(ROOT_DIR, 'frontend', 'src', 'tokens', 'tokens.js');

function resolveValue(tokenSet, ref) {
  if (typeof ref !== 'string' || !ref.startsWith('{') || !ref.endsWith('}')) {
    return ref;
  }
  const refPath = ref.slice(1, -1).split('.');
  let current = tokenSet;
  for (const part of refPath) {
    if (current && typeof current === 'object' && part in current) {
      current = current[part];
    } else {
      console.warn(`[build-tokens] Warning: Could not resolve token reference: ${ref}`);
      return ref;
    }
  }
  if (current && typeof current === 'object' && 'value' in current) {
    return resolveValue(tokenSet, current.value);
  }
  return typeof current === 'string' ? resolveValue(tokenSet, current) : current;
}

function kebabCase(str) {
  return str
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    .replace(/([A-Z])([A-Z][a-z])/g, '$1-$2')
    .toLowerCase();
}

function flattenTokens(obj, tokenSet, prefix = '') {
  const result = {};
  for (const key of Object.keys(obj)) {
    if (key.startsWith('$')) continue; // Skip schema and metadata
    const value = obj[key];
    const newPrefix = prefix ? `${prefix}-${kebabCase(key)}` : kebabCase(key);
    if (value && typeof value === 'object') {
      if ('value' in value) {
        result[newPrefix] = resolveValue(tokenSet, value.value);
      } else {
        Object.assign(result, flattenTokens(value, tokenSet, newPrefix));
      }
    }
  }
  return result;
}

export function buildTokens() {
  console.log(`[build-tokens] Reading ${TOKENS_JSON_PATH}...`);
  if (!fs.existsSync(TOKENS_JSON_PATH)) {
    console.error(`[build-tokens] Error: ${TOKENS_JSON_PATH} not found.`);
    process.exit(1);
  }

  const raw = fs.readFileSync(TOKENS_JSON_PATH, 'utf-8');
  const tokens = JSON.parse(raw);

  const globalTokens = tokens.global ? flattenTokens(tokens.global, tokens) : {};
  const componentTokens = tokens.component ? flattenTokens(tokens.component, tokens) : {};

  // Construct CSS output
  const lines = [
    '/**',
    ' * DO NOT EDIT MANUALLY.',
    ' * Generated by scripts/build-tokens.js from tokens.json (Tokens Studio / W3C DTCG Standard)',
    ' */',
    '',
    ':root {'
  ];

  lines.push('  /* Global Tokens: Typography, Spacing, Radius, Touch */');
  for (const [key, val] of Object.entries(globalTokens)) {
    lines.push(`  --${key}: ${val};`);
  }

  // Add backward-compatible aliases for e-Menu styles
  lines.push('');
  lines.push('  /* Semantic & Ergonomic Aliases */');
  if (globalTokens['spacing-xs']) lines.push(`  --space-xs: var(--spacing-xs);`);
  if (globalTokens['spacing-sm']) lines.push(`  --space-sm: var(--spacing-sm);`);
  if (globalTokens['spacing-md']) lines.push(`  --space-md: var(--spacing-md);`);
  if (globalTokens['spacing-lg']) lines.push(`  --space-lg: var(--spacing-lg);`);
  if (globalTokens['spacing-xl']) lines.push(`  --space-xl: var(--spacing-xl);`);
  if (globalTokens['spacing-2xl']) lines.push(`  --space-2xl: var(--spacing-2xl);`);

  if (globalTokens['border-radius-sm']) lines.push(`  --radius-sm: var(--border-radius-sm);`);
  if (globalTokens['border-radius-md']) lines.push(`  --radius-md: var(--border-radius-md);`);
  if (globalTokens['border-radius-lg']) lines.push(`  --radius-lg: var(--border-radius-lg);`);
  if (globalTokens['border-radius-xl']) lines.push(`  --radius-xl: var(--border-radius-xl);`);
  if (globalTokens['border-radius-pill']) lines.push(`  --radius-pill: var(--border-radius-pill);`);

  if (globalTokens['touch-target-min']) lines.push(`  --touch-target-min: var(--touch-target-min);`);
  if (globalTokens['touch-target-clearance']) lines.push(`  --touch-target-clearance: var(--touch-target-clearance);`);

  lines.push('');
  lines.push('  /* Component-Scoped Tokens */');
  for (const [key, val] of Object.entries(componentTokens)) {
    lines.push(`  --${key}: ${val};`);
  }
  lines.push('}');
  lines.push('');

  // Semantic Shop Themes
  if (tokens.semantic?.shop1) {
    lines.push('/* Shop 1 Theme (Gold Luxury) */');
    lines.push('.shop-theme-shop1 {');
    const shop1 = flattenTokens(tokens.semantic.shop1, tokens);
    if (shop1['primary']) lines.push(`  --primary-color: ${shop1['primary']};`);
    if (shop1['glow']) lines.push(`  --primary-glow: ${shop1['glow']};`);
    lines.push('}');
    lines.push('');
  }

  if (tokens.semantic?.shop2) {
    lines.push('/* Shop 2 Theme (Navy Dry Pastries) */');
    lines.push('.shop-theme-shop2 {');
    const shop2 = flattenTokens(tokens.semantic.shop2, tokens);
    if (shop2['primary']) lines.push(`  --primary-color: ${shop2['primary']};`);
    if (shop2['glow']) lines.push(`  --primary-glow: ${shop2['glow']};`);
    lines.push('}');
    lines.push('');
  }

  fs.writeFileSync(TOKENS_CSS_PATH, lines.join('\n'), 'utf-8');
  console.log(`[build-tokens] Generated ${TOKENS_CSS_PATH}`);

  // Construct JS output
  const resolvedTokens = {
    global: globalTokens,
    component: componentTokens,
    semantic: {
      shop1: tokens.semantic?.shop1 ? flattenTokens(tokens.semantic.shop1, tokens) : {},
      shop2: tokens.semantic?.shop2 ? flattenTokens(tokens.semantic.shop2, tokens) : {}
    }
  };

  const jsContent = [
    '/**',
    ' * DO NOT EDIT MANUALLY.',
    ' * Generated by scripts/build-tokens.js from tokens.json (Tokens Studio / W3C DTCG Standard)',
    ' */',
    '',
    `export const tokens = ${JSON.stringify(resolvedTokens, null, 2)};`,
    ''
  ].join('\n');

  fs.writeFileSync(TOKENS_JS_PATH, jsContent, 'utf-8');
  console.log(`[build-tokens] Generated ${TOKENS_JS_PATH}`);
  console.log(`[build-tokens] Build completed successfully.`);
}

// Execute if run directly from CLI
if (process.argv[1] === fileURLToPath(import.meta.url)) {
  buildTokens();
}
